import { TradeSpecialty, TradeSpecialtyId, ResourceTemplate } from '../types/trade.types';
import {
  Building2,
  Home,
  BrickWall,
  Hammer,
  SquareStack,
  Zap,
  Droplet,
  Wind,
  Paintbrush,
  Trees,
  DoorOpen,
  Wrench,
  Snowflake,
  Box,
  Trash2,
  Layers,
  FileStack,
  Shield,
  Fan,
  Sparkles,
  Cable,
  Power,
  Lightbulb,
  PanelTop,
  Settings,
  Gauge,
  Flame,
  TestTube,
  Scissors,
  Wrench as WrenchIcon,
  HardHat,
  TreePine,
  Sprout,
  Droplets,
  Fence,
  Thermometer,
  Gauge as GaugeIcon,
  Package,
  Container,
  Sofa,
  UtensilsCrossed,
  Wrench as WrenchIcon2,
} from 'lucide-react';

export const TRADE_SPECIALTIES: TradeSpecialty[] = [
  { id: 'general-construction', label: 'General Construction', labelEs: 'Obra civil' },
  { id: 'remodeling', label: 'Remodeling', labelEs: 'Renovación' },
  { id: 'masonry-concrete', label: 'Masonry & Concrete', labelEs: 'Albañilería y concreto' },
  { id: 'carpentry-framing', label: 'Carpentry & Framing', labelEs: 'Carpintería y estructura' },
  { id: 'drywall-ceilings', label: 'Drywall & Ceilings', labelEs: 'Tabla yeso y cielos' },
  { id: 'roofing', label: 'Roofing', labelEs: 'Techos' },
  { id: 'electrical', label: 'Electrical', labelEs: 'Electricidad' },
  { id: 'plumbing', label: 'Plumbing', labelEs: 'Plomería' },
  { id: 'hvac', label: 'HVAC & A/C', labelEs: 'Aire acondicionado' },
  { id: 'painting-finishing', label: 'Painting & Finishing', labelEs: 'Pintura y acabados' },
  { id: 'flooring', label: 'Flooring', labelEs: 'Pisos' },
  { id: 'landscaping-exteriors', label: 'Landscaping & Exteriors', labelEs: 'Jardinería y exteriores' },
  { id: 'windows-doors', label: 'Windows & Doors', labelEs: 'Ventanas y puertas' },
  { id: 'metal-welding', label: 'Metalwork & Welding', labelEs: 'Estructuras metálicas y soldadura' },
  { id: 'insulation', label: 'Insulation', labelEs: 'Aislamiento' },
  { id: 'interiors-cabinetry', label: 'Interiors & Cabinetry', labelEs: 'Interiores y mobiliario' },
];

export const RESOURCE_TEMPLATES: ResourceTemplate[] = [
  // Roofing
  {
    id: 'roof-tear-off',
    tradeId: 'roofing',
    label: 'Tear-off & Disposal',
    description: 'Existing roof removal and waste disposal',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'Trash2',
  },
  {
    id: 'roof-underlayment',
    tradeId: 'roofing',
    label: 'Underlayment',
    description: 'Waterproof membrane installation',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'Layers',
  },
  {
    id: 'roof-shingles',
    tradeId: 'roofing',
    label: 'Shingles',
    description: 'Asphalt shingle or sheet installation',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'FileStack',
  },
  {
    id: 'roof-flashing',
    tradeId: 'roofing',
    label: 'Flashing',
    description: 'Flashing and drip edge installation',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'Shield',
  },
  {
    id: 'roof-ventilation',
    tradeId: 'roofing',
    label: 'Ventilation',
    description: 'Roof ventilation (ridge vent / vents)',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'Fan',
  },
  {
    id: 'roof-cleanup',
    tradeId: 'roofing',
    label: 'Cleanup',
    description: 'Final cleanup and debris removal',
    defaultUnit: 'hr',
    defaultQuantity: 4,
    icon: 'Sparkles',
  },

  // Electrical
  {
    id: 'electrical-wiring',
    tradeId: 'electrical',
    label: 'Circuit Wiring',
    description: 'General circuit wiring',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'Cable',
  },
  {
    id: 'electrical-outlets',
    tradeId: 'electrical',
    label: 'Outlets',
    description: 'Electrical outlet installation',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'Power',
  },
  {
    id: 'electrical-switches',
    tradeId: 'electrical',
    label: 'Switches',
    description: 'Light switch installation',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'Settings',
  },
  {
    id: 'electrical-fixtures',
    tradeId: 'electrical',
    label: 'Light Fixtures',
    description: 'Light fixture installation',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'Lightbulb',
  },
  {
    id: 'electrical-panel',
    tradeId: 'electrical',
    label: 'Breaker Panel',
    description: 'Electrical breaker panel installation',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'PanelTop',
  },
  {
    id: 'electrical-labor',
    tradeId: 'electrical',
    label: 'Installation Labor',
    description: 'Installation labor and testing',
    defaultUnit: 'hr',
    defaultQuantity: 1,
    icon: 'Gauge',
  },

  // Plumbing
  {
    id: 'plumbing-water-lines',
    tradeId: 'plumbing',
    label: 'Water Lines',
    description: 'Cold/hot water pipe installation',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'Droplets',
  },
  {
    id: 'plumbing-drains',
    tradeId: 'plumbing',
    label: 'Drains',
    description: 'Drain installation',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'Droplet',
  },
  {
    id: 'plumbing-toilet',
    tradeId: 'plumbing',
    label: 'Toilet',
    description: 'Toilet installation',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'Droplet',
  },
  {
    id: 'plumbing-sink',
    tradeId: 'plumbing',
    label: 'Sink',
    description: 'Sink installation',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'Droplet',
  },
  {
    id: 'plumbing-water-heater',
    tradeId: 'plumbing',
    label: 'Water Heater',
    description: 'Water heater installation',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'Flame',
  },
  {
    id: 'plumbing-testing',
    tradeId: 'plumbing',
    label: 'Pressure Testing',
    description: 'Pressure testing and leak inspection',
    defaultUnit: 'hr',
    defaultQuantity: 2,
    icon: 'TestTube',
  },

  // Drywall
  {
    id: 'drywall-installation',
    tradeId: 'drywall-ceilings',
    label: 'Drywall Installation',
    description: 'Drywall panel supply and installation per m²',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'SquareStack',
  },
  {
    id: 'drywall-taping',
    tradeId: 'drywall-ceilings',
    label: 'Taping & Mudding',
    description: 'Joint taping and mudding',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'Scissors',
  },
  {
    id: 'drywall-texture',
    tradeId: 'drywall-ceilings',
    label: 'Texture',
    description: 'Texture application (if applicable)',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'Paintbrush',
  },
  {
    id: 'drywall-ceiling',
    tradeId: 'drywall-ceilings',
    label: 'Ceiling Installation',
    description: 'False ceiling / drywall ceiling installation',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'SquareStack',
  },
  {
    id: 'drywall-repair',
    tradeId: 'drywall-ceilings',
    label: 'Drywall Repair',
    description: 'Existing panel repair',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'WrenchIcon',
  },

  // Masonry & Concrete
  {
    id: 'masonry-foundation',
    tradeId: 'masonry-concrete',
    label: 'Concrete Foundation',
    description: 'Concrete foundation',
    defaultUnit: 'm³',
    defaultQuantity: 1,
    icon: 'Building2',
  },
  {
    id: 'masonry-block-wall',
    tradeId: 'masonry-concrete',
    label: 'Block Wall',
    description: 'Block or brick wall per m²',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'BrickWall',
  },
  {
    id: 'masonry-slab',
    tradeId: 'masonry-concrete',
    label: 'Concrete Slab',
    description: 'Concrete slabs',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'SquareStack',
  },
  {
    id: 'masonry-stucco',
    tradeId: 'masonry-concrete',
    label: 'Stucco',
    description: 'Wall stucco / plastering',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'Paintbrush',
  },
  {
    id: 'masonry-mortar',
    tradeId: 'masonry-concrete',
    label: 'Mortar & Mix',
    description: 'Mortar and mix',
    defaultUnit: 'm³',
    defaultQuantity: 1,
    icon: 'Package',
  },
  {
    id: 'masonry-labor',
    tradeId: 'masonry-concrete',
    label: 'Masonry Labor',
    description: 'Masonry labor',
    defaultUnit: 'hr',
    defaultQuantity: 1,
    icon: 'HardHat',
  },

  // Carpentry & Framing
  {
    id: 'carpentry-wall-frame',
    tradeId: 'carpentry-framing',
    label: 'Wall Framing',
    description: 'Wood framing for walls',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'SquareStack',
  },
  {
    id: 'carpentry-roof-frame',
    tradeId: 'carpentry-framing',
    label: 'Roof Framing',
    description: 'Roof structure framing',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'Home',
  },
  {
    id: 'carpentry-doors',
    tradeId: 'carpentry-framing',
    label: 'Wood Doors',
    description: 'Wood door installation',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'DoorOpen',
  },
  {
    id: 'carpentry-trim',
    tradeId: 'carpentry-framing',
    label: 'Trim & Molding',
    description: 'Frame and molding installation',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'Scissors',
  },
  {
    id: 'carpentry-cabinets',
    tradeId: 'carpentry-framing',
    label: 'Built-in Cabinets',
    description: 'Built-in furniture / closets',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'Box',
  },

  // Painting & Finishing
  {
    id: 'painting-prep',
    tradeId: 'painting-finishing',
    label: 'Surface Prep',
    description: 'Surface preparation (sanding, cleaning)',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'Scissors',
  },
  {
    id: 'painting-primer',
    tradeId: 'painting-finishing',
    label: 'Primer',
    description: 'Sealer or primer application',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'Paintbrush',
  },
  {
    id: 'painting-interior',
    tradeId: 'painting-finishing',
    label: 'Interior Paint',
    description: 'Interior wall paint per m²',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'Paintbrush',
  },
  {
    id: 'painting-exterior',
    tradeId: 'painting-finishing',
    label: 'Exterior Paint',
    description: 'Exterior facade paint',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'Paintbrush',
  },
  {
    id: 'painting-trim',
    tradeId: 'painting-finishing',
    label: 'Trim Paint',
    description: 'Door/molding paint',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'Paintbrush',
  },
  {
    id: 'painting-labor',
    tradeId: 'painting-finishing',
    label: 'Painting Labor',
    description: 'Painting labor',
    defaultUnit: 'hr',
    defaultQuantity: 1,
    icon: 'Gauge',
  },

  // Flooring
  {
    id: 'flooring-tile',
    tradeId: 'flooring',
    label: 'Ceramic Tile',
    description: 'Ceramic tile floor installation',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'SquareStack',
  },
  {
    id: 'flooring-laminate',
    tradeId: 'flooring',
    label: 'Laminate/Vinyl',
    description: 'Laminate or vinyl floor installation',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'Layers',
  },
  {
    id: 'flooring-hardwood',
    tradeId: 'flooring',
    label: 'Hardwood',
    description: 'Hardwood floor installation',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'TreePine',
  },
  {
    id: 'flooring-leveling',
    tradeId: 'flooring',
    label: 'Surface Leveling',
    description: 'Surface leveling',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'GaugeIcon',
  },
  {
    id: 'flooring-baseboard',
    tradeId: 'flooring',
    label: 'Baseboards',
    description: 'Baseboard / skirting installation',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'Scissors',
  },

  // Landscaping & Exteriors
  {
    id: 'landscaping-grass',
    tradeId: 'landscaping-exteriors',
    label: 'Grass/Sod',
    description: 'Natural or synthetic grass / sod',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'Sprout',
  },
  {
    id: 'landscaping-plants',
    tradeId: 'landscaping-exteriors',
    label: 'Plants & Garden',
    description: 'Gardening and plants',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'Trees',
  },
  {
    id: 'landscaping-irrigation',
    tradeId: 'landscaping-exteriors',
    label: 'Irrigation System',
    description: 'Irrigation system installation',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'Droplets',
  },
  {
    id: 'landscaping-paths',
    tradeId: 'landscaping-exteriors',
    label: 'Paths & Pavement',
    description: 'Exterior paths and pavement',
    defaultUnit: 'm²',
    defaultQuantity: 1,
    icon: 'SquareStack',
  },
  {
    id: 'landscaping-fence',
    tradeId: 'landscaping-exteriors',
    label: 'Fencing',
    description: 'Fence installation',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'Fence',
  },

  // HVAC
  {
    id: 'hvac-unit',
    tradeId: 'hvac',
    label: 'AC Unit',
    description: 'Air conditioning unit installation',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'Snowflake',
  },
  {
    id: 'hvac-ducts',
    tradeId: 'hvac',
    label: 'Ductwork',
    description: 'Duct installation',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'Wind',
  },
  {
    id: 'hvac-thermostat',
    tradeId: 'hvac',
    label: 'Thermostat',
    description: 'Thermostat installation',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'Thermometer',
  },
  {
    id: 'hvac-refrigerant',
    tradeId: 'hvac',
    label: 'Refrigerant Charge',
    description: 'Refrigerant charge',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'GaugeIcon',
  },
  {
    id: 'hvac-mounting',
    tradeId: 'hvac',
    label: 'Mounting & Supports',
    description: 'Mounts and supports',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'Wrench',
  },

  // Interiors & Cabinetry
  {
    id: 'cabinetry-kitchen',
    tradeId: 'interiors-cabinetry',
    label: 'Kitchen Cabinets',
    description: 'Kitchen cabinet installation',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'UtensilsCrossed',
  },
  {
    id: 'cabinetry-closets',
    tradeId: 'interiors-cabinetry',
    label: 'Closets',
    description: 'Closet installation',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'Container',
  },
  {
    id: 'cabinetry-custom',
    tradeId: 'interiors-cabinetry',
    label: 'Custom Furniture',
    description: 'Custom furniture installation',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'Sofa',
  },
  {
    id: 'cabinetry-countertops',
    tradeId: 'interiors-cabinetry',
    label: 'Countertops',
    description: 'Countertop installation',
    defaultUnit: 'm',
    defaultQuantity: 1,
    icon: 'SquareStack',
  },
  {
    id: 'cabinetry-hardware',
    tradeId: 'interiors-cabinetry',
    label: 'Hardware',
    description: 'Hardware installation',
    defaultUnit: 'pza',
    defaultQuantity: 1,
    icon: 'WrenchIcon2',
  },
];

